apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-examen
  namespace: db-oswaldo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-examen
  template:
    metadata:
      labels:
        app: db-examen
    spec:
      containers:
        - name: db-examen
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: db-examen