apiVersion: v1
kind: Service
metadata:
  name: db-examen
  namespace: db-oswaldo
  labels:
    app: db-examen
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: db-examen