apiVersion: v1
kind: Service
metadata:
    name: api-examen
    namespace: api-oswaldo
spec:
    selector:
        app: api-examen
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
          nodePort: 30000
    type: NodePort
